### ISSUE TITLE
Blocked host: templatus-hotwire.test

### ISSUE THREAD

**Issue by kornate** [templatus/templatus-hotwire#1319]
Thanks for sharing your great work as open source! 🚀

Carefully following the README setup guide on MacOS, this occurs after step 5:

> Following your setup tutorial Blocked host: templatus-hotwire.test
> To allow requests to templatus-hotwire.test make sure it is a valid hostname (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:
> 
> config.hosts << "templatus-hotwire.test"
> For more details view: [the Host Authorization guide](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization)

In `.env`, changing `APP_HOST=templatus-hotwire.example.com` to `APP_HOST=templatus-hotwire.test`, and running `bin/setup` again fixes this.

But it doesn't seem this is the intended way things should work for the development environment? Perhaps there needs to be a `.env.dev`, or the README needs updating for clarity.

**Comment by ledermann** [comment]
You are absolutely right, thanks for pointing this out!

I just added `.env.development` for shared (= not secret) settings, so now it works out of the box.

**Comment by kornate** [comment]
Wow! That was sueperhumanly fast!

Thank you - hopefully it will help others get started and discover this great tool, which took some digging to find! (on the ruby slim gem page, no less!) 

Please don't replace it with haml!
