### ISSUE TITLE
unknown app

### ISSUE THREAD

**Issue by voodoo** [templatus/templatus-hotwire#1859]
Interesting/sophisticated setup, hopefully I can get it to work. 
------

Mac m1 air  version 14.4 (23E214) Sonoma

# bin/dev

http://vite.templatus-hotwire.test:3036/vite-dev/

Is working. 

# rails s

go to localhost:3000

Gives me "unknown app"

And all localhost:3000 is redirected to.  https://templatus-hotwire.test

(I've been out of the rails biz for sometime, and used to be reasonably competent, hopefully this is not too stupid.)

**Comment by ledermann** [comment]
This project uses [vite-ruby](https://vite-ruby.netlify.app/) and [puma-dev](https://github.com/puma/puma-dev), so you need to set up the local domain (see [README](https://github.com/templatus/templatus-hotwire?tab=readme-ov-file#install-for-development)) and start the app with `bin/dev`. The app will then be available at `https://templatus-hotwire.test/`. 

The oldskool url `http://localhost:3000` does not work.
